Factorized code
SynthesisLab/LTLISynthesis pull request #1
Opened 2024-11-27 15:42 UTC by bmouillon

2024-11-28 08:13 UTC, GBathie requested changes
Merci Baptiste, c'est ce qu'on attendait !
Voir quelques commentaires ci-dessous.

2024-11-28 08:13 UTC, GBathie commented on code/ltli6463factorized.cu
> +        if (op == 'U') {
Au lieu de faire des cas 'U' et 'pas U', je propose réduire la redondance du code de la manière suivante : "toujours faire le calcul gauche-droite" puis "si c'est 'U', faire le calcul droite-gauche". (De manière générale, "si c'est un opérateur binaire non commutatif, faire le calcul droite-gauche".)

Tu peux même réutiliser CS1 dans le if pour le calcul droite-gauche.

2024-11-28 08:13 UTC, GBathie commented on code/ltli6463factorized.cu
> +        printf("Opérateur non pris en charge: %c\n", op);
Il vaudrait mieux level une exception ici. (Mais cette branche va disparaître, voir commentaire sur la définition de OP en tant que char)

2024-11-28 08:13 UTC, GBathie commented on code/ltli6463factorized.cu
> +    char op,
Tu as défini ici `op` comme un caractère : c'est valide, mais ça pose le problème des caractères qui ne sont pas des opérateurs valides.
Il vaudrait mieux utiliser un `enum` ici, ça permet de s'assurer qu'il n'y a pas de valeurs illégales.

Aussi, dans la version actuelle, le test de l'opérateur se fait à l'execution avec le switch.
On pourrait gagner un peu en performance en changeant ce check au compile time.
Il faut mettre `op` en paramètre de template, puis remplacer les `case`s du  `switch` par des `if constexpr`.

```suggestion
template<Operator op>
__device__ void applyOperator(
    // ...
```
et plus bas
```c++
if constexpr (op == Until) {
    // Implémentation de Until
} else if constexpr (op == ...) {
// ...
}

```

2024-11-29 14:17 UTC, bmouillon commented on code/ltli6463factorized.cu
> +        if (op == 'U') {
C'est fait, je ne l'avais pas fait au début parce que le fait de devoir faire deux opérations décalait aussi les indices. Du coup j'ai juste modifié tid avec une condition.

2024-11-29 14:17 UTC, bmouillon commented on code/ltli6463factorized.cu
> +    char op,
C'est fait, et du coup j'ai supprimé le default case dans applyOperator.

2024-11-29 14:55 UTC, bmouillon commented on code/ltli6463factorized.cu
> +            else {
J'ai modifié le formatter de VSCode pour qu'il mette les else sur la même ligne. S'il y a encore des choses qui ne vont pas, tu peux le signaler, je peux à peu près tout moduler.

2024-11-29 15:04 UTC, GBathie requested changes
Looks good to me, un dernier changement à faire sur la fonction qui applique les opérateurs, pour faire plus de choses au compile time.

2024-11-29 15:04 UTC, GBathie commented on code/ltli6463factorized.cu
> +    case Op::Not: {
Ici, même si `op` est passé en argument de template, le switch est (il me semble) évalué au runtime. Pour s'assurer que c'est évalué au compile-time, il faut remplacer ce switch par une chaîne de `if constexpr (cond1) {...} else if constexpr (condn) {...} else`

2024-11-29 15:16 UTC, GBathie requested changes

2024-11-29 15:16 UTC, GBathie commented on code/ltli6463factorized.cu
>          break;
Tu peux enlever les breaks !

2024-11-29 15:16 UTC, GBathie commented on code/ltli6463factorized.cu
> +    } else {
Ici ça serait bien de mettre un commentaire pour préciser que c'est le cas Until.
Encore mieux, mettre encore un if constexpr pour until, et dans le else final, mettre un static assert(false), ou quelque chose comme ça, qui empêcherait la compilation avec un opérateur qui n'est pas pris en charge par cette fonction.

2024-11-29 16:13 UTC, merged